
//register

POST http://localhost:3030/auth/register
Content-Type: application/json

{
    "username" : "ahmed",
    "password" : "eddy"
}
################
//login

POST http://localhost:3030/auth/login
Content-Type: application/json

{
    "username" : "ahmed",
    "password" : "eddy"
}